Volleyball\Bundle\AttendeeBundle\Entity\Level:
    type: entity
    table: level
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        description:
            type: string
            nullable: true
        special:
            type: boolean
            options:
                default: false
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    fields: { name }
        created:
            type: date
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        attendees:
            targetEntity: Volleyball\Bundle\AttendeeBundle\Entity\Attendee
            mappedBy: level
        organizations:
            targetEntity: Volleyball\Bundle\OrganizationBundle\Entity\Organization
            mappedBy: level            
