Volleyball\Bundle\AttendeeBundle\Entity\Position:
    type: entity
    table: attendee_position
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        description:
            type: string
            nullable: true
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    fields: { name }
        created:
            type: date
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        attendees:
            targetEntity: Volleyball\Bundle\AttendeeBundle\Entity\Attendee
            mappedBy: attendee_position
    manyToOne:
        organization:
            targetEntity: Volleyball\Bundle\OrganizationBundle\Entity\Organization
            inversedBy: attendee_position
            joinColumn:
                name: organization_id
                referencedColumnName: id